var hierarchy =
[
    [ "gslc_tsCollect", "structgslc__tsCollect.html", null ],
    [ "gslc_tsColor", "structgslc__tsColor.html", null ],
    [ "gslc_tsDriver", "structgslc__tsDriver.html", null ],
    [ "gslc_tsElem", "structgslc__tsElem.html", null ],
    [ "gslc_tsElemRef", "structgslc__tsElemRef.html", null ],
    [ "gslc_tsEvent", "structgslc__tsEvent.html", null ],
    [ "gslc_tsEventTouch", "structgslc__tsEventTouch.html", null ],
    [ "gslc_tsFont", "structgslc__tsFont.html", null ],
    [ "gslc_tsGui", "structgslc__tsGui.html", null ],
    [ "gslc_tsImgRef", "structgslc__tsImgRef.html", null ],
    [ "gslc_tsInputMap", "structgslc__tsInputMap.html", null ],
    [ "gslc_tsKey", "structgslc__tsKey.html", null ],
    [ "gslc_tsPage", "structgslc__tsPage.html", null ],
    [ "gslc_tsPt", "structgslc__tsPt.html", null ],
    [ "gslc_tsRect", "structgslc__tsRect.html", null ],
    [ "gslc_tsXCheckbox", "structgslc__tsXCheckbox.html", null ],
    [ "gslc_tsXGauge", "structgslc__tsXGauge.html", null ],
    [ "gslc_tsXGlowball", "structgslc__tsXGlowball.html", null ],
    [ "gslc_tsXGlowballRing", "structgslc__tsXGlowballRing.html", null ],
    [ "gslc_tsXGraph", "structgslc__tsXGraph.html", null ],
    [ "gslc_tsXKeyPad", "structgslc__tsXKeyPad.html", null ],
    [ "gslc_tsXKeyPadCfg", "structgslc__tsXKeyPadCfg.html", null ],
    [ "gslc_tsXKeyPadCfg_Alpha", "structgslc__tsXKeyPadCfg__Alpha.html", null ],
    [ "gslc_tsXKeyPadCfg_Num", "structgslc__tsXKeyPadCfg__Num.html", null ],
    [ "gslc_tsXKeyPadData", "structgslc__tsXKeyPadData.html", null ],
    [ "gslc_tsXKeyPadResult", "structgslc__tsXKeyPadResult.html", null ],
    [ "gslc_tsXListbox", "structgslc__tsXListbox.html", null ],
    [ "gslc_tsXProgress", "structgslc__tsXProgress.html", null ],
    [ "gslc_tsXRadial", "structgslc__tsXRadial.html", null ],
    [ "gslc_tsXRamp", "structgslc__tsXRamp.html", null ],
    [ "gslc_tsXRingGauge", "structgslc__tsXRingGauge.html", null ],
    [ "gslc_tsXSeekbar", "structgslc__tsXSeekbar.html", null ],
    [ "gslc_tsXSelNum", "structgslc__tsXSelNum.html", null ],
    [ "gslc_tsXSlider", "structgslc__tsXSlider.html", null ],
    [ "gslc_tsXSpinner", "structgslc__tsXSpinner.html", null ],
    [ "gslc_tsXTemplate", "structgslc__tsXTemplate.html", null ],
    [ "gslc_tsXTextbox", "structgslc__tsXTextbox.html", null ],
    [ "gslc_tsXTogglebtn", "structgslc__tsXTogglebtn.html", null ],
    [ "THPoint", "classTHPoint.html", null ],
    [ "TouchHandler", "classTouchHandler.html", [
      [ "TouchHandler_XPT2046", "classTouchHandler__XPT2046.html", null ]
    ] ]
];